# ===================================
# PostgreSQL Connection Configuration
# ===================================
db.url=jdbc:postgresql://localhost:5432/scootersRental_d?currentSchema=scooters
db.username=postgres
db.password=postgres

# ===================================
# HikariCP Connection Pool
# ===================================
db.pool.maximumPoolSize=10
db.pool.minimumIdle=2
db.pool.connectionTimeout=30000
db.pool.idleTimeout=600000
db.pool.maxLifetime=1800000

# ????????? ??? ???? Hibernate
logging.level.org.hibernate=OFF
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.engine.jdbc=OFF
logging.level.org.hibernate.engine.transaction=OFF
logging.level.org.hibernate.engine.jdbc.env=OFF
logging.level.org.hibernate.engine.jdbc.spi=OFF
logging.level.org.hibernate.resource=OFF
logging.level.org.hibernate.resource.transaction=OFF
logging.level.org.hibernate.resource.jdbc=OFF
logging.level.org.hibernate.loader=OFF
logging.level.org.hibernate.event=OFF
logging.level.org.hibernate.internal=OFF
logging.level.org.hibernate.persister=OFF
logging.level.org.hibernate.tool=OFF
logging.level.org.hibernate.transaction=OFF
logging.level.org.hibernate.context=OFF
logging.level.org.hibernate.service=OFF
logging.level.org.hibernate.cache=OFF
logging.level.com.zaxxer.hikari=OFF